pool:
  name: 'Default'
  demands:
    - agent.name -equals INES

variables:
  dockerHubServiceConnection: 'docker'  # Your DockerHub service connection
  frontendImageName: 'ineskouki/frontend'  # Frontend Docker image name

resources:
  repositories:
    - repository: frontend_repo
      type: git
      name: PFE/connector-frontend-demo

trigger:
  branches:
    include:
      - master  # Trigger pipeline on changes to master branch

stages:
  - stage: Checkout_And_Install_Node
    displayName: 'Checkout Frontend Code and Install Node.js'
    jobs:
    - job: CheckoutAndInstallNode
      displayName: 'Checkout Frontend Code and Install Node.js'
      steps:
      - checkout: frontend_repo
        displayName: 'Checkout Frontend Repository'

      - task: NodeTool@0
        inputs:
          versionSpec: '20.x'
        displayName: 'Install Node.js (20.x)'

  - stage: NPM_Install_And_Build
    displayName: 'Install npm Packages and Build Angular Project'
    dependsOn: Checkout_And_Install_Node
    jobs:
    - job: NpmInstallAndBuild
      displayName: 'npm Install and Build Angular Project'
      steps:
      - script: |
          npm install -g @angular/cli@15
          npm install
          ng build --prod
        displayName: 'npm install and build with Angular CLI v15'

  - stage: Build_And_Push_Docker_Image
    displayName: 'Build and Push Frontend Docker Image'
    dependsOn: NPM_Install_And_Build
    jobs:
    - job: BuildAndPushDocker
      displayName: 'Build and Push Frontend Docker Image'
      steps:
      - task: Docker@2
        inputs:
          containerRegistry: $(dockerHubServiceConnection)
          repository: $(frontendImageName)
          command: buildAndPush
          Dockerfile: 'Dockerfile'
          buildContext: '$(Build.SourcesDirectory)'
          tags: |
            latest
        displayName: 'Build and Push Frontend Docker Image'
